DATABASE_SERVER_URI : "127.0.0.1"
DATABASE_USER : "database_user"
DATABASE_PORT: 5432
DATABASE_PASSWORD : "password"
DATABAS_NAME : "idr"
CACHE_FOLDER : "path/to/folder/app_data"
CELERY_BROKER_URL : "redis://localhost:6379"
CELERY_RESULT_BACKEND : "redis://localhost:6379"
ASYNCHRONOUS_SEARCH : True
ELASTICSEARCH_URL : "http://localhost:9200"
PAGE_SIZE : 10000
MAX_RETUNED_ITEMS : 1700000
